spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lsg?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

    
server:
  port: 8081
  context-path: /lsg